[package]
name = "boundedVecOptimized"
type = "bin"
authors = ["Ahmed Elghareeb (ahmed.elghareeb@epfl.ch)"]

[dependencies]
noir_base64 = { tag = "v0.4.2", git = "https://github.com/noir-lang/noir_base64" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
